### ISSUE TITLE
Using stop() still changes the URL to the next path

### ISSUE THREAD

**Issue by jasongrishkoff** [VeliovGroup/flow-router#62] opened 2019-02-18 09:14 UTC
When firing `stop()` inside of the global `triggers.exit`, the expected behavior is that the user is not taken to the next route.  From what I can see, FlowRouter still updates all its internals to reflect that we're on the new route, even though the page doesn't actually change.

```
FlowRouter.triggers.exit([pageChange])
```

```
pageChange = function(context,redirect,stop) {                                                                        
   if (context.path.indexOf('step=') > -1                                                                         
        && !confirm('Are you sure you want to leave this page?'                                                       
            + ' You haven\'t finished yet.')                                                          
    ) {
        stop()
    }
}
```

This guy seems to have had a similar problem and solved it, but the pull request was never merged?
https://github.com/kadirahq/flow-router/pull/681

**Comment by dr-dimitru** [comment] 2019-03-23 07:35
Hello @jasongrishkoff ,

Very sorry for late reply. Could you describe in more details in more details, is the URL in the browser get changed? Is the new template get rendered?

__Note:__ You can't call `stop()` from async callback

**Comment by jasongrishkoff** [comment] 2019-03-23 20:32
The URL gets changed, but the template does not get rendered.

**Comment by dr-dimitru** [comment] 2019-03-23 22:01
@jasongrishkoff do you have any errors or exceptions in a browser/server console? Sound's like routing was interrupted by something

**Comment by dr-dimitru** [comment] 2019-03-25 22:36
@jasongrishkoff let me know if you have more details or it's got solved.

**Comment by jasongrishkoff** [comment] 2019-03-26 06:59
There are no errors in the browser/server console.

**Comment by dr-dimitru** [comment] 2019-03-27 21:11
@jasongrishkoff Minimal reproduction would help a lot. Marked [help wanted]

**Comment by dr-dimitru** [comment] 2019-04-27 01:45
Hey @jasongrishkoff,

I believe right after you call `.stop()` you should redirect to other route or render another template.
Described behavior matching expected as `.stop()` will interrupt routing chain of actions, in your case interruption happens between changing URI and rendering new template.

Feel free to close it in case if the issue is solved on your end.

**Comment by jasongrishkoff** [comment] 2019-04-27 17:41
To me, "stop" would imply that I want to cancel my routing and stay where I am.  The fact that it only fires *after* the URI has changed seems wrong.  I've already used a workaround, so in a sense this is solved.

**Comment by dr-dimitru** [comment] 2019-04-27 18:00
@jasongrishkoff would you share your workaround?

**Comment by jasongrishkoff** [comment] 2019-04-27 18:28
I basically just trigger the back button.
```
FlowRouter.triggers.enter([loaderBar,pageChange])
```
```
pageChange = function(context,redirect,stop) {
  if (!confirm('Are you sure you want to leave this page?') {
    stop()
    setTimeout(() => { window.history.back() })
  }
}
```

**Comment by dr-dimitru** [comment] 2019-04-27 22:42
@jasongrishkoff thank you.

We did additional checking, there is no easy way (*or at least we haven't found any*) to change this behavior, this part remained unchanged from original flow router.

**Closed as completed by dr-dimitru** 2019-04-27 22:42 UTC
Labels: question
