### ISSUE TITLE
Yield not staying in div or honouring its initial position. 

### ISSUE THREAD

**Issue by CyberCyclone** [VeliovGroup/flow-router#91] opened 2021-09-12 04:34 UTC
I'm having issues with the yield statement not staying in it's assigned div.

```
FlowRouter.route('/', {
	action() {
		// Render a template using Blaze
		this.render('Page_body', 'Page_home', {menu: 'menu'});
	}
});
```

```
<body class="g-sidenav-show bg-gray-100">
	{{> yield}}
	<!--   Core JS Files   -->
	<script src="/assets/js/plugins/threejs.js"></script>
</body>
```

```
<template name="Page_body">
	{{> menu}}
	<main class="main-content border-radius-lg ">
		{{> main}}
		{{> yield }}
	</main>	
</template>
```

Basically, I need to have the <body> statement at the root because I must have the class statements with it.

Page_body then needs to be added to the html body by the yield.

Page_home then needs to be added to the Page_body yield.

The problem is that on first render, the yield in Page_body stays within the <main> tag which is what is needed, but as soon as I run a different route, it pops out of the <main> and gets dumped at the bottom of the <body> tag. This seems to be the case with any use case of yield not honouring its initial position.

**Comment by dr-dimitru** [comment] 2021-09-16 18:40
@CyberCyclone this is Blaze issue not honoring template location on re-render; This is known issue, template won't honor its location within sibling elements; Recommended approach to always have wrapping parent element

Hope that helps

**Comment by dr-dimitru** [comment] 2022-06-03 13:46
My answer looks straightforward. Perhaps it is fixed in the latest Blaze release. I'm working on compatibility release. Feel free to reopen it in case if the issue is still persists on your end.

**Closed as completed by dr-dimitru** 2022-06-03 13:46 UTC
Labels: question
