### ISSUE TITLE
Elasticsearch + Flow Router

### ISSUE THREAD

**Issue by vpl-webteam** [VeliovGroup/flow-router#50] opened 2018-06-25 15:04 UTC
I am using elasticsearch for a search engine on our website with a react ui package from [searchkit](https://github.com/searchkit/searchkit). The react package works based on the URL. When you use the filters for search it works correctly and filters to show the correct items. (url "/resorts?state[0]=Florida&state[1]=Texas")

Then when you click on the item it redirects you to the correct page, ("/resort/:resortId") but then when you try to go back ("/resorts?state[0]=Florida&state[1]=Texas") after a filter it stays on the redirected page. 

You can only go back to the filter page after clicking back multiple times to the original main search. ("/resorts")

```
FlowRouter.route('/resorts/', {
  action: function (params, queryParams) {
      console.log(params, queryParams);
      
      mount(MainLayout, {
        content: () => (
            <ListOfResorts />
        ) 
      })
    }
});
```

ostrio:flow-router-extra@3.5.0
METEOR@1.6.1
All browsers and platforms

No errors in the console

**Comment by dr-dimitru** [comment] 2018-07-11 20:11
Hello @vpl-webteam ,

I'm sorry for late reply. Do you still experiencing this issue?
If so, I need more info to help you:
 1. How exactly redirect is implemented? 

As I understood `/resorts?getQuery` redirects to `/resort/:resortId`. And when you trying to go back to `/resorts?getQuery` (*by clicking back button*), it redirects you again to `/resort/:resortId`, and only if you click back button quickly without giving a chance to FR to catch navigation you can pass it over.

If all above sounds correct, bad news  -  this is actually expected behavior.
And here is good news - there is a way to remove `/resorts?getQuery` from history, and actually go to page before (*lets say - go -2*).

Here is some links for inspiration:
 - https://developer.mozilla.org/en-US/docs/Web/API/History_API
 - https://stackoverflow.com/questions/28028297/js-window-history-delete-a-state
 - http://html5doctor.com/history-api/

Let me know wdyt.

**Comment by vpl-webteam** [comment] 2018-07-11 20:21
Yes still experiencing the issue.

The only part you are missing is that the user clicks on an item to go to the resort. They are seperate pages. `/resorts/?getQuery` is a search page. `/resort/:resortId` is an individual page. No matter how long you wait when you click back to view the previous search results it stays on the individual page until you reach the `/resorts/` without the query.

**Comment by dr-dimitru** [comment] 2018-07-11 21:27
@vpl-webteam 

 1. What exact code do you use for redirect?
 2. How user gets to the `/resorts/?getQuery` page, and how get query is set?

**Comment by vpl-webteam** [comment] 2018-07-12 13:43
Its in production. https://vacationpropertiesforless.com/resorts

Click on a few filters on the left side then the url and content changes.
After adding filters you can click on a single resort and it goes to that
page. When you click back it wont load the url query.

**Comment by dr-dimitru** [comment] 2018-07-12 19:49
@vpl-webteam could you please share a code you used behind the scene, for:

 1. Redirect?
 2. How query parameters are set?

**Comment by vpl-webteam** [comment] 2018-07-16 14:51
1. `FlowRouter.go('resort', {resortId: this.props.id})` I also tried `FlowRouter.go('/resort/' + props.Resort._id)` both act the same.
2. Url path is set using searchkit (https://github.com/searchkit/searchkit)

**Comment by dr-dimitru** [comment] 2018-07-26 10:52
Hey @vpl-webteam ,

We just released [`v3.5.1`](https://github.com/VeliovGroup/flow-router/releases/tag/3.5.1), not sure if your specific issue would be fixed, but it worth trying.

But I would look into `searchkit` docs and try to disable it to hack into `document.location` and `history`, as you use *FlowRouter*, only *FlowRouter* should manipulate History API.

**Comment by dr-dimitru** [comment] 2018-07-26 10:53
Marked as `[helpwanted]`, hope someone from community members has faced the same issue and would help us here. It might be a good idea to repost it to the forums.meteor.com

**Comment by dr-dimitru** [comment] 2019-04-27 01:59
Hey @vpl-webteam  👋
Have you found a solution so far?

**Comment by dr-dimitru** [comment] 2022-06-03 13:33
Cleaning up here. Feel free to reopen it in case if the issue is still persists on your end.

**Closed as completed by dr-dimitru** 2022-06-03 13:33 UTC
Labels: help wanted, question, react
