### ISSUE TITLE
Variable & optional prefix group

### ISSUE THREAD

**Issue by arichter83** [VeliovGroup/flow-router#61] opened 2019-02-06 21:25 UTC
I have optional partners in my scenario which get a specific site, but all the routes stay the same. E.g.:
```
/ => homepage no partner
/create => subpage no partner
/one/ => homepage partner one
/one/create => subpage partner one
etc.
```

The list of partners is limited and will not collide with the subpages, so I created it like this:
```javascript
var group = FlowRouter.group({
  prefix: "/:partner(one|two|three)?"
})
group.route("/", {name: "base", ...)
group.route("/create", {name: "create", ...)
```

For this the pipe `|` is missing in the `Router.pathRegExp` and I created a PR https://github.com/VeliovGroup/flow-router/pull/60

Also I was thinking of a method to make this partner "sticky" for all further `FlowRouter.go()`, etc. calls and wondered if I am missing an option in the existing code. My implementation would be like the following:

```javascript
  sticky_field = 'partner'
  path(_pathDef, fields = {}, queryParams) {
    // Keep a sticky field
    if(this.sticky_field && !fields[this.sticky_field]
        && this._current.params && this._current.params[this.sticky_field]) {
      fields[this.sticky_field] = this._current.params[this.sticky_field]
    }
```

Do you think that a similar implementation would be of value to others?

**Comment by dr-dimitru** [comment] 2019-02-06 22:29
Hello @arichter83 ,

 1. I your case it seem to use more logical approach making "partner" as subpath `/:partner/:partnerName?`
 2. `pathRegExp` is editable by default — [see docs](https://github.com/VeliovGroup/flow-router/blob/master/docs/api/pathRegExp.md), and addressed in #25, asn solver in #28 by @nicooprat

Although I've merged your PR, now thinking — are we really want to publish such changes?
Waiting for your opinion @arichter83

**Comment by arichter83** [comment] 2019-02-06 23:23
Dear @dr-dimitru,

the PR was just the `|` and I think it is optional to merge and no need to publish. I didn't know about the overriding!

And in regards to the `sticky_field`, that was just a draft. But `/:partner/:partnerName?` is no solution - `/:partner(one|two|three)?` means `/`, `/one`, `/two` or `/three`.

**Comment by dr-dimitru** [comment] 2019-02-07 00:19
Okay, going to revert latest merge. Please, feel free to use `pathRegExp` to meet your needs 😉

Feel free to reopen it in case if the issue is still persists on your end.

**Closed as completed by dr-dimitru** 2019-02-07 00:19 UTC
Labels: enhancement
